version: '3.8'
services:
  sql-common:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-common
    environment:
      SA_PASSWORD: "YourStrongPassw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "14331:1433"
    networks:
      - sqlnet

  sql-footage:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-footage
    environment:
      SA_PASSWORD: "YourStrongPassw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "14332:1433"
    networks:
      - sqlnet

networks:
  sqlnet:
    driver: bridge